# Generated by Django 2.2.6 on 2019-10-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ingredients', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=500)),
            ],
        ),
    ]
