# Generated by Django 2.2.6 on 2019-11-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
